apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wg-easy.fullname" . }}-data
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.pvName }}
  volumeName: {{ .Values.storage.pvName | quote }}
  {{- end }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
