apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wg-easy.fullname" . }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
data:
  PASSWORD: {{ .Values.wgEasy.adminPassword | b64enc | quote }}
