apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webdav.fullname" . }}
  labels:
    {{- include "webdav.labels" . | nindent 4 }}
data:
  config.yaml: |
    address: 0.0.0.0
    port: 80
    auth: {{ .Values.auth.enabled }}
    {{- if .Values.auth.enabled }}
    users:
      {{- toYaml .Values.auth.users | nindent 6 }}
    {{- end -}}

